# -*- coding: utf-8 -*-
"""extractcaption.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zNTK2MCUYNfdlQnB1hnCS1LyIo5hNHSy

# MedVid QnA
"""

!pip install youtube_transcript_api

import numpy as np
import pandas as pd
import json
from youtube_transcript_api import YouTubeTranscriptApi

trainF = open('train.json')
train = json.load(trainF)

print(train)

for row in train:
  try:
    transcript_list = YouTubeTranscriptApi.list_transcripts(row['video_id'])
    transcript = transcript_list.find_generated_transcript(['en'])
    transcript = transcript.fetch()
    text =""
    for moment in transcript:
      text= text + " "+ moment['text']
    row['transcript'] = text
  except:
    row['transcript'] = "Subtitles are disabled for this video"

print(train[0])

for row in train:
  if row['label'] == "Medical Non-instructional":
    row['label'] = [1,0]
  if row['label'] == "Medical Instructional":
    row['label'] = [1,1]
  if row['label'] == "Non-medical":
    row['label'] = [0,0]

total = 0
without =0

for row in train:
  total=total+1
  if row['transcript'] == "Subtitles are disabled for this video":
    without=without+1



with open("train_transcripts.json", "w") as outfile:
  json.dump(train, outfile)